services:
  traefik:
    image: "traefik:v2.11.2"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  pihole:
    container_name: pihole
    domainname: eaton.home
    image: "pihole/pihole:latest"
    platform: "linux/arm/v6"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns:
      - 127.0.0.1
      - 9.9.9.9
    volumes:
      - ./services/pihole/pihole/:/etc/pihole/
      - ./services/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    environment:
      ServerIP: 192.168.4.254
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.eaton.home
      TZ: "America/Chicago"
      PIHOLE_DNS: 9.9.9.9;149.112.112.112;1.1.1.1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.eaton.home`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=web"

  whoami:
    image: "containous/whoami:v1.4.0"
    platform: "linux/arm/v6"
    container_name: "simple-service"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`eaton.home`)"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24