services:
  pihole:
    container_name: pihole
    domainname: eaton.home
    image: "pihole/pihole:latest"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns:
      - 127.0.0.1
      - 9.9.9.9
    volumes:
      - $DOCKERDIR/services/pihole/data:/etc/pihole/
      - $DOCKERDIR/services/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    env_file: $DOCKERDIR/.env
    restart: unless-stopped
    networks:
      traefik_proxy:
        ipv4_address: 192.168.90.100
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.eaton.home`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.docker.network=docker_traefik_proxy"