services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - socket_proxy
    command: -H tcp://socket-proxy:2375
    ports:
      - "9000:9000"
    volumes:
      - $DOCKERDIR/services/portainer/data:/data
    environment:
      - TZ=$TZ