services:
  traefik:
    container_name: traefik
    image: traefik:latest
    security_opt:
      - no-new-privileges:true
    networks:
      traefik_proxy:
        ipv4_address: 192.168.90.254
      socket_proxy:
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik_proxy 
      - --providers.docker.swarmMode=false
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --entrypoints.web.address=:80
      - --entrypoints.traefik.address=:8080
      - --log=true
      - --log.filePath=/logs/traefik.log
      - --log.level=DEBUG
      - --accessLog=true
      - --accessLog.filePath=/logs/access.log
      - --accessLog.bufferingSize=100
      - --accessLog.filters.statusCodes=204-299,400-499,500-599
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    restart: unless-stopped
    volumes:
      # - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$DOCKERDIR/services/traefik/logs:/logs"